# Generated by Django 4.1.7 on 2023-03-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('AFM', models.IntegerField(default=0, unique=True)),
                ('AMKA', models.IntegerField(default=0, unique=True)),
                ('address', models.CharField(default='', max_length=128)),
                ('dateOfBirth', models.DateField(null=True)),
                ('age', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=64)),
                ('last_name', models.CharField(default='', max_length=64)),
                ('address', models.CharField(default='', max_length=254)),
                ('age', models.IntegerField(default=1)),
                ('AFM', models.IntegerField(default=None, null=True, unique=True)),
                ('employee_externalPartner', models.CharField(choices=[('Υπάλληλος', 'Υπάλληλος'), ('Εξωτερικός', 'Εξωτερικός')], default='', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Insurers',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_of_contract', models.CharField(choices=[('Ζωής', 'Ζωής'), ('Οχήματος', 'Οχήματος'), ('Πυρός', 'Πυρός'), ('Αστικής Ευθύνης', 'Αστικής Ευθύνης')], default='', max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('insurance_company', models.CharField(choices=[('Εθνική', 'Εθνική'), ('NN', 'NN'), ('Groupama', 'Groupama')], default='', max_length=64)),
                ('renew_date', models.DateField(null=True)),
                ('dateOfPublish', models.DateField(null=True)),
                ('duration', models.CharField(choices=[('Ετήσια', 'Ετήσια'), ('Εξάμηνη', 'Εξάμηνη'), ('Τρίμηνη', 'Τρίμηνη')], max_length=64)),
                ('payment_method', models.CharField(choices=[('Ετήσια', 'Ετήσια'), ('Εξάμηνη', 'Εξάμηνη'), ('Τρίμηνη', 'Τρίμηνη')], max_length=64)),
                ('insurance_premiums', models.FloatField(default=0, null=True)),
                ('insurance_code', models.IntegerField(default=0, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.customer')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.insurer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='insurer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.insurer'),
        ),
    ]
